[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']

[tool.isort]
profile = "black"

[flake8]
max-line-length = 88
exclude = ['.git', '__pycache__', 'old' ,'build', 'dist', '.venv']
