[tool.black]
line-length = 79
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']

[tool.isort]
profile = "black"

[flake8]
max-line-length = 79
exclude = ['.git', '__pycache__', 'old' ,'build', 'dist', '.venv']
