Version: "3"

Services:
  { self.container }:
    image: ubuntu
    volumes:
      - ./agent_dev_volume:/src
    working_dir: /src
    poirts:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
